# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FOV_Data_overview_designer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 30, 91, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.channelBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.channelBox.setObjectName("channelBox")
        self.verticalLayout.addWidget(self.channelBox)
        self.waveBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.waveBox.setObjectName("waveBox")
        self.verticalLayout.addWidget(self.waveBox)
        self.deltaBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.deltaBox.setObjectName("deltaBox")
        self.verticalLayout.addWidget(self.deltaBox)
        self.parameters = QtWidgets.QLabel(self.centralwidget)
        self.parameters.setGeometry(QtCore.QRect(20, 10, 81, 16))
        self.parameters.setObjectName("parameters")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 121, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.channel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.channel.setScaledContents(False)
        self.channel.setObjectName("channel")
        self.verticalLayout_2.addWidget(self.channel)
        self.wavelength = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.wavelength.setObjectName("wavelength")
        self.verticalLayout_2.addWidget(self.wavelength)
        self.delta = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.delta.setObjectName("delta")
        self.verticalLayout_2.addWidget(self.delta)
        self.figurePlot = QtWidgets.QGraphicsView(self.centralwidget)
        self.figurePlot.setGeometry(QtCore.QRect(240, 30, 401, 311))
        self.figurePlot.setObjectName("figurePlot")
        self.graphicLabel = QtWidgets.QLabel(self.centralwidget)
        self.graphicLabel.setGeometry(QtCore.QRect(410, 10, 59, 16))
        self.graphicLabel.setObjectName("graphicLabel")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(240, 370, 211, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.loadingLabel = QtWidgets.QLabel(self.centralwidget)
        self.loadingLabel.setGeometry(QtCore.QRect(250, 350, 101, 16))
        self.loadingLabel.setObjectName("loadingLabel")
        self.directoryText = QtWidgets.QTextEdit(self.centralwidget)
        self.directoryText.setGeometry(QtCore.QRect(130, 410, 511, 20))
        self.directoryText.setObjectName("directoryText")
        self.WDLabel = QtWidgets.QLabel(self.centralwidget)
        self.WDLabel.setGeometry(QtCore.QRect(10, 410, 141, 16))
        self.WDLabel.setObjectName("WDLabel")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 651, 441))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.azimuthCheckBox = QtWidgets.QCheckBox(self.frame)
        self.azimuthCheckBox.setGeometry(QtCore.QRect(20, 210, 87, 20))
        self.azimuthCheckBox.setAutoExclusive(True)
        self.azimuthCheckBox.setObjectName("azimuthCheckBox")
        self.zenithCheckBox = QtWidgets.QCheckBox(self.frame)
        self.zenithCheckBox.setGeometry(QtCore.QRect(20, 240, 87, 16))
        self.zenithCheckBox.setAutoExclusive(True)
        self.zenithCheckBox.setObjectName("zenithCheckBox")
        self.loadData = QtWidgets.QPushButton(self.frame)
        self.loadData.setGeometry(QtCore.QRect(120, 180, 113, 32))
        self.loadData.setObjectName("loadData")
        self.plotFOV = QtWidgets.QPushButton(self.frame)
        self.plotFOV.setGeometry(QtCore.QRect(120, 220, 113, 32))
        self.plotFOV.setObjectName("plotFOV")
        self.frame.raise_()
        self.verticalLayoutWidget.raise_()
        self.parameters.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.figurePlot.raise_()
        self.graphicLabel.raise_()
        self.progressBar.raise_()
        self.loadingLabel.raise_()
        self.directoryText.raise_()
        self.WDLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen_directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_directory.setObjectName("actionOpen_directory")
        self.actionClose_2 = QtWidgets.QAction(MainWindow)
        self.actionClose_2.setObjectName("actionClose_2")
        self.menuFile.addAction(self.actionOpen_directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.setNativeMenuBar(False)  # include menu in window (on mac)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FOV Data Overview"))
        self.parameters.setText(_translate("MainWindow", "Parameters"))
        self.channel.setText(_translate("MainWindow", "channel"))
        self.wavelength.setText(_translate("MainWindow", "wavelength"))
        self.delta.setText(_translate("MainWindow", "delta"))
        self.graphicLabel.setText(_translate("MainWindow", "Graphic"))
        self.loadingLabel.setText(_translate("MainWindow", "loading data"))
        self.WDLabel.setText(_translate("MainWindow", "Working directory"))
        self.azimuthCheckBox.setText(_translate("MainWindow", "azimuth"))
        self.zenithCheckBox.setText(_translate("MainWindow", "zenith"))
        self.loadData.setText(_translate("MainWindow", "Plot data"))
        self.plotFOV.setText(_translate("MainWindow", "Plot FOV"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionOpen_directory.setText(_translate("MainWindow", "open directory"))
        self.actionClose_2.setText(_translate("MainWindow", "close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

